# Define a 'Persistent Volume Claim'(PVC) for elastic-search Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-search-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: elastic-search
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 3Gi    #This will tell kubernetes about the amount of space we are trying to claim.
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-search
  labels:
    app: elastic-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-search
  template:
    metadata:
      labels:
        app: elastic-search
    spec:
      containers:
        - name: elastic-search
          image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
          env: 
            - cluster.name=k8s-elastic-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"        
          ports:
          - containerPort: 9200

          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 512Mi
              cpu: "0.2"
      volumes:
        - name: elastic-search-persistent-storage # Obtaining 'volume' from PVC
          persistentVolumeClaim:
            claimName: elastic-search
--- 
apiVersion: v1
kind: Service
metadata:  
  name: elastic-search
spec:
  type: NodePort
  selector:
    app: elastic-search
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      # nodePort: 30010           