apiVersion: v1
kind: Service
metadata:  
  name: hello-ui-service
spec:
  type: NodePort  
  selector:
    app: hello-ui-con
  ports:
    - protocol: TCP
      # nodePort: 30101
      port: 4200
      targetPort: 80