apiVersion: v1
kind: Service
metadata:  
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello-con
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      # nodePort: 30010