apiVersion: v1
kind: Service
metadata:  
  name: hello-lb-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'   
spec:
  type: LoadBalancer
  selector:
    app: hello-con
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081